version: "3.7"

services:
  caddy:
    image: caddy:latest
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: './Caddyfile'
        target: /etc/caddy/Caddyfile
        read_only: true
      - ./sites:/usr/share/caddy
      - ./caddy_data:/data
      - ./caddy_config:/config
